---
title: "WildAid Site Map"
author: "Elise Gonzales"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the required libraries
```{r}
library(leaflet)
library(dplyr)
library(googlesheets4)
library(janitor)
library(stringi)
library(leaflet.extras)
```

# Read data from CSV file
```{r}
# Read in Data ---- 
#url for site list 
url <- "https://docs.google.com/spreadsheets/d/1945sRz1BzspN4hCT5VOTuiNpwSSaWKxfoxZeozrn1_M/edit?usp=sharing"

sites <- read_sheet(url) |> 
  clean_names() |> 
  select(site, latitude, longitude, status, active_site) |> 
  separate(status, into = c("status_numb", "status_key"), sep = " - ") |> 
  mutate(status_numb = as.numeric(status_numb)) |> 
  filter(active_site == "current")
  
```

# Define your scoring scale and associated colors
```{r}
score_scale <- c(1, 2, 3, 4, 5, 6)  # Example scoring scale
color_palette <- c("#00A6A6", "#7FB069", "#094074", "#F4D067", "#E88B84", "#E17000")
status_word <- c("1: Discovery", "2: Partnership", "3: Enforcement design", "4: Implimentation", "5: Mentorship", "6: Regional Leadership")

# make a little dataframe to join the colors to the number column 
color_df <- data.frame(status_numb = score_scale, 
                       colors = color_palette, 
                       word = status_word)

# left join to the status_numb column 
sites_w_color <- left_join(sites, color_df, by = "status_numb")
```


# Create a function to map scores to colors ----
```{r}
# not necessary for now: 
# score_to_color <- function(score) {
#   color_idx <- findInterval(score, score_scale, all.inside = TRUE)
#   return(color_palette[color_idx])
# }
```


# Create a leaflet map
```{r}
map <- leaflet(sites) %>%
  addTiles() %>% # Add default tile layers
   
  addCircleMarkers(data = sites_w_color, 
                   lat = ~latitude, 
                   lng = ~longitude, 
                   radius = 10, 
                   color = ~colors,
                    label = ~as.character(site),
                   # Use the score_to_color function to map scores to colors,  Set label as site name
                   fillOpacity = 0.8) %>%
  setView(lng = -9.4919, lat = 30.6081, zoom = 1.5) %>% # Set initial map view
  addLegend(colors = color_palette,
            labels = status_word,
            position = "bottomright")
```
# Print the map
```{r}
map
```


